[[chapter3]]

== RISC-V security building blocks

This chapter outlines brief descriptions of RISC-V security building blocks
discussed in this specification, together with general guidelines and links to
technical specifications. The requirement to use a specific mechanism is
use case dependent. RISC-V has multiple mechanisms that can be used to achieve the
same goal, the notes associated with SRs indicate where this is the case.

See also the reference use cases chapter of this specification for common
examples of how RISC-V security building blocks can be combined.

=== Isolation

Isolation enables access restrictions on software components executing on a hart, as well
as on device accesses. RISC-V enables:

* Privilege based isolation
* Physical memory access control (hart and device-initiated accesses)
* Virtual memory management (hart and device virtualization)
* Hypervisor extension
* Supervisor domains

==== Privilege levels

*See section 1.2 (Privilege Levels) of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

Standard privilege levels - machine mode (M-Mode), supervisor mode (S-Mode), and user
mode (U-Mode) - enable separation of more privileged software from less privileged
software.

==== Hypervisor extension

*See chapter 8 (Hypervisor Extension) of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

The Hypervisor extension supports standard supervisor level hypervisors. It extends
S-Mode into Hypervisor-extended supervisor mode (HS-Mode), and a virtual supervisor
mode (VS-Mode) for guests. It also extends U-Mode into standard user mode (U-Mode) and
virtual user mode (VU-Mode).

Isolation of guests is enforced using two-stage address translation and
protection.  Two-stage address translation and protection is in effect in VS-Mode
and VU-Mode.

[#cat_sr_sub_hyp]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_HYP_001
| For virtualised environments, Hypervisor extension MUST be supported

|===


Alternatively SPMP can be used instead of MMU to support static partitioning
hypervisors, for example on systems with hard and deterministic real time
requirements.

MMU, PMP/Smepmp, and SPMP are discussed later in this chapter.

==== PMA

*See section 3.6 (Physical Memory Attributes) of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

_Physical memory attributes (PMA)_ are intended to capture inherent properties
of the underlying hardware. For example, read-only ROM regions, or non-cacheable
device regions. Often PMA can be fixed at design time or at boot, but sometimes
runtime PMA can be required.

A separate hardware checker - _PMA checker_ - enforces PMA rules at runtime once
a physical address is known. PMA rules are always checked on every physical
access, and typically configured by region.

==== PMP

*See section 3.7 (Physical Memory Protection) of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

_Physical memory protection (PMP)_ enables M-Mode to access-control physical
memory for supervisor and U modes (with or without H-extension).

[#cat_sr_sub_pmp]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_001
| PMP configurations MUST only be directly accessible to machine mode
| SR_PMP_002
| PMP/smepmp MUST be used to isolate M-Mode from lower privilege levels
|===

NOTE: Individual access controlled regions can be locked until the next system reset
to create temporal isolation boundaries, such as protecting immutable boot code.
Depending on the use case, MPT may be an acceptable additional or alternative mechanism to the PMP/smepmp

==== Smepmp

*See chapter 6 (PMP Enhancements for memory access and execution prevention in machine mode) of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

Smepmp extends PMP protection by allowing machine mode to restrict its own access to memory allocated to lower privilege levels. This can be
used to mitigate against privilege escalation attacks.

[#cat_sr_sub_smepmp]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_003
| If PMP is supported then Smepmp MUST be supported.
|===

==== SPMP

_This extension is not ratified at the time of writing, but is stable enough to be included_

*See the https://github.com/riscv/riscv-spmp[RISC-V S-Mode Physical Memory Protection (SPMP)] specification.*

_Supervisor PMP (SPMP)_ enables supervisor mode to control physical memory
access for U mode.

SPMP allows supervisor mode to restrict its own access to memory allocated to
lower privilege levels. This can be used to mitigate against privilege
escalation attacks, for example.

When combined with H-extension, SPMP can be nested so that the hypervisor can
control memory allocations to its guests, and each guest can control its own
memory allocations to its workloads.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_004
| SPMP MUST be used to protect S-Mode from lower privilege levels.

| SR_PMP_005
| SPMP MUST be used to protect U-mode workloads from other U-mode workloads.

| SR_PMP_006
| SPMP configurations MUST only be directly accessible to machine mode and supervisor mode
|===

NOTE: Dependent on the use case, it may be recommended or mandatory to use SPMP to protect supervisor mode from lower privilege levels (with or without the H-extension). The MMU may be an additional or alternative mechanism.

NOTE: Dependent on the use case, Trusted Execution Environments may require or recommend the use of SPMP to isolate trusted applications from each other.
The MMU may be an additional or alternative mechanism


==== MMU

*See sections 4.3 to 4.6 (Page-Based Virtual-Memory Systems) of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

_Memory management unit (MMU)_ enables address translation and protection for:

* Isolating an OS from workloads, and workloads from each other on a system without H-extension (one-stage
translation)
* Isolating a hypervisor from a guest, on a system with H-extension (two-stage
translation)

[#cat_sr_sub_mmu]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_MMU_001
| if the Sv extension is supported then 1st-stage page tables MUST be used to protect
the S-Mode Supervisor domain from accesses made by U-Mode.

| SR_MMU_002
| if the H extension is supported 1st-stage and/or G-stage page tables MUST be used to protect
Supervisor domain H/S-mode from lower privilege levels.

| SR_MMU_003
| MMU MUST be used to protect resources assigned to one workload from other workloads
|===

NOTE: Dependent on the use case, it may be recommended or mandatory to use MMU to protect supervisor mode from lower privilege levels (with or without the H-extension). The SPMP and PMP may be an additional or alternative mechanism.

NOTE: Dependent on the use case, Trusted Execution Environments may require or recommend the use of MMU to isolate trusted applications from each other. The SPMP and PMP may be an additional or alternative mechanism.

==== Address‑Independent Latency of Faults 

To prevent timing side channels that may infer the address space layout of supervisor memory, user-mode accesses to supervisor-mode memory must raise and exception in constant time. The Svukte extension ensures instruction fetches and explicit memory accesses from U-Mode to S-Mode addresses generate page faults independent of the target address, mitigating this timing attack.

[#cat_sr_sub_KTE]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_KTE_001
| Svukte MUST be used to mitigate timing attacks arising from user mode access to supervisor mode memory
|===

==== Supervisor domains and MPT

_This extension is not ratified at the time of writing, but is stable enough to be included_

*See the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor domains access
protection] specification.*

Supervisor domains allow software components on the same hart to be developed,
certified, deployed, and attested independently of each other.

A supervisor domain is an S-Mode compartment that is physically isolated from other supervisor domains. The memory,
execution state and devices belonging to a supervisor domains are isolated from other supervisor domains.
This isolation of supervisor domains and the context switching between them is managed by M-Mode firmware.

A supervisor domain is identified at an architecture level by a _Supervisor Domain
ID (SDID)_ held in the _mmpt_ CSR, managed by M-Mode firmware. In addition to
the SDID, the mmpt CSR may specify a root PPN for a _Memory Protection Table (MPT)_.

The MPT is a memory structure managed by machine
mode that is used to manage physical memory permissions across supervisor domains.
It is designed to enable page-based dynamic memory management across supervisor
domain boundaries.
responsible for resource management.

[#cat_sr_sub_mtt]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_MPT_001
| MPT MUST be used to isolate M-Mode from lower privilege
levels

| SR_MPT_002
| MPT configurations MUST only be directly accessible to machine mode.

|===


NOTE: The M-Mode resident software responsible for managing context switches and communication between supervisor
domains is called the Root Domain. Depending on the use case, MPT can
be sufficient for protecting the Root Domain by enabling M-Mode
to ensure that its own resources are never assigned to any another domain.
PMP/Smepmp may be an additional or alternative protection for M-Mode, enabling the ability to
implement temporal isolation boundaries within M-Mode (to protect
early boot code, for example), or to prevent itself from accessing or executing from memory
assigned to lower privilege levels (privilege escalation).

[cat_sr_sub_sud]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_SUD_001
| MPT MUST be used to enforce physical memory isolation
boundaries for supervisor domains, and to protect machine mode from any
supervisor domain.

| SR_SUD_002
| PMP/Smepmp MUST be used to enforce physical memory isolation
boundaries for supervisor domains, and to protect machine mode from any
supervisor domain.

|===

NOTE: PMP can be used for more static and deterministic use cases.
MPT can be used where more fine grained (page-based) dynamic resource management across
supervisor domain boundaries is required.

===== Supervisor domain resource access and sharing


[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_SUD_003
| MPT MUST be used to protect resources assigned to one supervisor domain from other supervisor domains

| SR_SUD_004
| Resources assigned to a higher trust level supervisor domain MUST NOT be accessible
to an lower trust level supervisor domain. The trust levels/policies are specified by the
security system designer.

| SR_SUD_005
| Resources assigned to an untrusted supervisor domain MUST be accessible to a trusted supervisor domain
|===

Supervisor domains allow resource isolation and sharing between domains under the control of M-Mode firmware. Trusted Execution Environments can require asymmetric sharing models, where one trusted domain has X/W/R access to other domain's resources.

===== Supervisor domain debug

[width=100%]
[%header, cols="5,20"]
|===

| ID#
| Requirement

| SR_SUD_006
| A system supporting supervisor domains MUST support supervisor domain
extensions for interrupts (Smsdia).

| SR_SUD_007
| A system supporting supervisor domains MUST support supervisor domain
extensions for external debug (TBD).
|===

*See chapter 6 (Smsdia) of the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor
Domains Access Protection] specification.*

==== External debug and performance counters

*See the https://github.com/riscv-non-isa/riscv-external-debug-security[RISC-V External Debug Security Extension]
specification.*

[cat_sr_sub_dbg]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_DBG_001
| External debug MUST only be enabled by HW RoT (M-Mode external debug) or by FW
RoT (non M-Mode external debug).

| SR_DBG_002
| External debug MUST be enabled separately for M-Mode & non-M-Mode software.

| SR_DBG_003
| Self-hosted debug MUST be used for debug of non M-Mode software.

| SR_DBG_004
| Self-hosted debug MUST only be enabled by a higher privileged component.

|===

NOTE: Systems with the same ownership between M-Mode and non-M-Mode software may choose to enable external debug for all software or none.
Other trust models may require external debug be enabled for non-M-Mode software without affecting M-Mode (recoverable debug).
Where external debug is not enabled, systems may use an S-Mode OS to enable self-hosted debug for a user application without affecting other applications or S-Mode itself.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_DBG_005
| FW RoT MUST disable self-hosted debug for all non M-Mode software.

|===

NOTE: A secure system may require disabling self-hosted debug in a production system for certification
reasons.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_DBG_006
| External debug MUST only be enabled following system reset (part of measuring)
of the affected component, moderated by a RoT.

| SR_DBG_007
| Revealing self-hosted debug MUST only be enabled following reboot (part of
measuring) of the affected component.

| SR_DBG_008
| Trusted self-hosted debug enabled at runtime (after measuring) of the
affected component, MUST be subject to an application specific governance process.

|===

NOTE: Enabling debug after measurement ensures the system remains attestable but can affect the
confidentiality and trustworthiness of the affected components, and must be subject to an attested policy

*See chapters 7 and 9 of the https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification on performance counters.*

These extensions enable management of interrupts, external debug, and
performance counters across supervisor domain boundaries.

==== IOPMP

_This extension is not ratified at the time of writing, but is stable enough to be included_

*See the https://github.com/riscv-non-isa/iopmp-spec[RISC-V IOPMP] specification.*

IOPMP is a system level component providing physical memory access control for
device-initiated transactions, complementing PMP and SPMP rules.

[#cat_sr_sub_iop]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOP_001
| A system which supports PMP/Smepmp, or SPMP, MUST implement either IOPMP or
World for device access control.

| SR_IOP_002
| IOPMP configurations MUST only be directly accessible to machine mode.

| SR_IOP_003
| IOPMP MUST be used to guarantee that devices assigned to lower privilege levels cannot access resources assigned to M-Mode.

| SR_IOP_004
| IOPMP MUST be used to guarantee that devices assigned to a domain cannot be accessed by other domains.

|===

NOTE: IOPMP defines multiple "models" for different system configurations.
Unless specified differently in the use cases in this specification, system
designers are free to choose any IOPMP model. Depending on the use case, IOMPT may be an alternative or addition to IOPMP

==== IOMPT

_This extension is not ratified at the time of writing, but is stable enough to be included_

*See the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor domains access
protection] specification.*

IOMPT is a system level component providing physical memory access control for
device-initiated transactions, by mapping transactions to IOMMU translation and MPT permissions.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOM_001
| A system which supports MPT MUST implement IOMPT for access-control for
device-initiated memory accesses.

| SR_IOM_002
| IOMPT configurations MUST only be directly accessible to machine mode.

| SR_IOM_003
| IOMPT MUST be used to guarantee that devices assigned to lower privilege levels cannot access resources assigned to M-Mode.

| SR_IOM_004
| IOMPT MUST be used to guarantee that devices assigned to a domain cannot be accessed by other domains.

|===

NOTE: IOMPT can be sufficient for protecting Root devices as M-Mode can enforce that its own resources are never assigned to another domain.
Depending on the use case, IOPMP may be an alternative or addition to IOMPT. For example, a system
may require that Root devices are not able to access memory assigned to TEE domain.

==== IOMMU

_This extension is not ratified at the time of writing, but is stable enough to be included_

*See the https://github.com/riscv-non-isa/riscv-iommu[RISC-V IOMMU] specification.*

IOMMU is a system level component performing memory address translation from IO
Virtual Addresses to Physical Addresses thereby allowing devices to access virtual memory
locations. It complements the MMU.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOM_006
| Systems supporting MMU MUST also support IOMMU

|===

NOTE: Systems using IOMMU must ensure this cannot be used to bypass physical
memory access controls by implementing IOPMP or IOMPT.

==== Worlds

_This extension is not ratified at the time of writing, but is stable enough to be included_

*See the https://github.com/riscv/riscv-worlds[RISC-V Worlds] specification.*

Worlds defines execution context IDs (or world IDs) which allow different
access policies to be programmed between an agent and a resource in a system.
The IDs are created and assigned before or at reset/boot time, and are
immutable afterwards. Any bus transaction stemming from an agent within a world
always carries its world ID.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_WOR_001
| RISC-V Worlds MUST be used to indicate execution contexts.

| SR_WOR_002
| Worlds configurations MUST only be performed by a trusted entity in the system.

| SR_WOR_003
| If IOPMP is implemented it MUST use the World ID to determine the context of a
transaction to enforce isolation of resources.

| SR_WOR_004
| M-Mode boot firmware, that configures the hart, MUST lock the mwid CSR at the
earliest possible boot stage (Smwid).

| SR_WOR_005
| If a hart supports multiple privilege levels, world IDs MUST be used to
guarantee that devices assigned to a world ID with a higher privilege level
cannot be accessed by world IDs from lower privilege levels (Smlwid).

| SR_WOR_006
| If a hart supports multiple privilege levels, world IDs used by machine-mode
MUST not be delegated to lower privilege levels (Smlwidlist).

| SR_WOR_007
| If a hart supports supervisor mode, world IDs used by supervisor-mode MUST
not be delegated to user-mode (Smwdeleg).

|===

=== Software enforced memory tagging

*See Chapter 25 of https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged ISA] specification.*

_Memory tagging (MT)_, is a technique which can improve the memory safety of an
application. A part of the effective address of a pointer can be masked off
and used as a tag indicating the intended ownership or state of a pointer. The tag
can be used to track accesses across different regions as well as protecting
against pointer misuse such as "use-after-free". Pointer masking implementations should use
the proposed RISC-V pointer masking extension (Smmpm, Smnpm, Ssnpm).

With software based memory tagging the access rules encoded in tags are
enforced by software, such as the compiler and the application runtime.

See also hardware enforced memory tagging below.

=== Control flow integrity

*See chapter 23 of https://github.com/riscv/riscv-isa-manual/releases/latest[Privileged
ISA] specification.*

Control-flow Integrity (CFI) capabilities help defend against Return-Oriented
Programming (ROP) and Call/Jump-Oriented Programming (COP/JOP) style of
control-flow subversion attacks. Here an attacker attempts to modify return
addresses or call/jump address to redirect a victim to code used by the
attacker.

These attack methodologies use code sequences in authorized modules, with at
least one instruction in the sequence being a control transfer instruction that
depends on attacker-controlled data either in the return stack or in memory
used to obtain the target address for a call or jump.

Attackers stitch these
sequences together by diverting the control flow instructions (e.g., JALR,
C.JR, C.JALR), from their original target address to a new target via
modification in the return stack or in the memory used to obtain the jump/call
target address.

RISC-V provides two defenses:

* Shadow stacks (Zicfiss) - protect return addresses on call stacks
* Labeled Landing pads (Zicfilp) - protect target addresses in jumps and
branches

=== Cryptography

*See Chapters 31 and 32 of https://github.com/riscv/riscv-isa-manual/releases/latest[Unprivileged
ISA] specification.*

RISC-V includes ISA extensions in the following cryptographic areas:

* Scalar cryptography
* Vector cryptography
* Entropy source (scalar)

RISC-V cryptographic extensions are aimed at supporting efficient acceleration
of cryptographic operations at the ISA level. This can both help reduce the TCB of
an isolated component and also avoid hardware bottlenecks (for example, system
level cryptographic subsystems).

The entropy source extension provides an ISA level interface to a hardware
entropy source. Entropy source requirements can depend on use case or ecosystem
specific requirements and RISC-V does not provide any entropy source technical
specification. However, the entropy source ISA specification does contain general
recommendations and references.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_CPT_001
| RISC-V systems MUST support either scalar or vector cryptographic ISA
extensions

| SR_CPT_002
| RISC-V systems SHALL support vector cryptographic ISA
extensions

| SR_CPT_003
| The entropy source ISA extension MUST be supported 

|===

NOTE: Depending on use case and system architecture, cryptographic extensions may be mandatory. If either scalar or vector cryptographic ISA extensions are supported, then an entropy source would usually also be considered mandatory. It is not necessary to support both scalar and vector operations, as a scalar operation can be viewed as a vector of size 1. If no cryptographic extensions are supported, then some use cases may still require the entropy source extension.


=== Architectural metadata storage

In the context of this document, _architectural metadata_ refers to any data that is implicitly trusted by the architecture. Storage of such data is referred to as _architectural metadata storage_.

Examples (not exhaustive) where architectural metadata may be required in current or future RISC-V architecture include:  MTT, memory tagging, and CHERI.

Architectural metadata storage is implementation defined, but the following rules should be considered by any implementation.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_AMS_001
| Architectural metadata storage MUST be protected against logical attacks

| SR_AMS_002
| Architectural metadata storage MUST be protected against physical attacks

| SR_AMS_003
| Architectural metadata storage MUST be protected against direct attacks

|===

See xref:chapter2.adoc#_adversarial_model[adversarial model]

For example, architectural metadata storage may be implemented in on-chip memory, or in cryptographically protected external DDR.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_AMS_004
| Architectural metadata MUST be isolated by privilege level, and within supervisor domain boundaries

|===

Depending on the use case, architectural metadata may be visible to or managed by, for example, a supervisor level kernel or hypervisor, a kernel or a hypervisor within a supervisor domain, or by a machine mode monitor. But it should be considered private within an isolation boundary and not accessible or guessable by lower privilege levels, or by code in a different supervisor domain.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_AMS_005
| Cryptographically protected architectural metadata storage MUST provide privacy protection, including at least location freshness and boot freshness

| SR_AMS_006
| Cryptographically protected architectural metadata storage MUST provide error detection

| SR_AMS_007
| Cryptographically protected architectural metadata storage MUST provide integrity protection

| SR_AMS_008
| Cryptographically protected architectural metadata storage MUST provide replay protection or temporal freshness

|===

NOTE: Architectural metadata needs to be protected against both unauthorized access (read or modify), boot attacks, relocation attacks, and errors (accidental or malicious).

NOTE: On systems where architectural metadata is stored in external memory, and external memory attacks are in scope (for example, directly accessible or replaceable external memory), then cryptographic protection with replay protection or temporal freshness is strongly recommended.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_AMS_009
| Architectural metadata storage MUST be protected against indirect attacks

|===

NOTE: In general, protection against indirect attacks is a system implementation problem not specific to architectural metadata storage. For example, systems supporting speculative execution should also implement appropriate mitigations against speculation based attacks. Any such mitigations should also be applied to the implementation of architectural metadata storage.


=== Extensions in development



==== Post quantum cryptography

*See https://github.com/riscv/riscv-pqc[RISC-V Specification for Post-quantum Cryptography].*

The _RISC-V Post Quantum Cryptography_ initiative aims to specify ISA extensions that enhance performance and
implementation efficiency for contemporary public-key cryptography, with a focus on standard Post-Quantum Cryptography
algorithms like ML-KEM (FIPS-203), ML-DSA (FIPS-204), SLH-DSA (FIPS-205) and others. The ISA design and evaluation prioritize the requirements of real-world
networked devices, ensuring that the Post-Quantum Cryptography (PQC) extensions effectively complement existing scalar
and vector cryptography extensions.

==== High assurance cryptography

*See https://github.com/riscv/riscv-hac[RISC-V Specification for High Assurance Cryptography].*

The High Assurance Cryptography task group will create instruction set extensions (ISEs) that facilitate higher levels of assurance than the existing Scalar and Vector Crypto ISEs. One initial focus will be on full-rounds vector AES extensions that allow (do not prevent) effective side-channel resistant implementations and that may perform better than the existing round-based instructions, with future work on other algorithms. A second intimately related focus area will be ISEs that manage secret keys -- not restricted to just AES keys -- in ways that better protect them from unauthorized users and from side-channel analysis.

==== Hardware Memory Tagging

*See  https://github.com/riscv/riscv-memory-tagging[RISC-V Memory Tagging].*

To address memory safety issues, the Memory Tagging task group will define a mechanism for tagged pointer construction, tag management instructions to store tags and tag checks on memory accesses (pointer dereferences), and a tag storage mechanism in virtual memory along with protection mechanisms for tag storage.

==== Timing Fences

*See https://github.com/riscv/riscv-timing-fences[Timing Fences].*

The fence.time instruction is a proposed RISC-V ISA extension designed to mitigate timing covert channels by managing shared microarchitectural states. Timing covert channels exploit the timing of events to leak sensitive information across security boundaries, such as between privilege levels or processes. This working group will propose a mechanism for software to signal hardware to prevent the sharing of microarchitectural state during security domain switches

==== Speculation Barriers

*See https://github.com/riscv/spec-barrier[Speculation Barriers].*

Speculative execution attacks exploit vulnerabilities in modern processors that use speculative execution to improve performance. These attacks, such as Spectre and Meltdown, manipulate the CPU's speculative behavior to access sensitive data that should be inaccessible. Although the speculative operations are eventually discarded, the changes they make to system state can be measured and used to infer confidential information. This task group will propose a mechanism for software to signal hardware when not to speculate.


=== Capability based architecture

==== CHERI

*See the https://github.com/riscv/riscv-cheri[RISC-V Specification for CHERI Extensions] specification.*

CHERI - an ISA technique that uses capability-based memory protection for spatial and temporal memory safety, compartmentalization, and control-flow enforcement.  Source code has to be recompiled to capture memory safety properties inherent in the source language.

